INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Não Somos Mendigos', 'https://rederuasp.files.wordpress.com/2017/08/cropped-13041255_1022453481173057_7646186484742796767_o.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Situações de Ruas', 'https://i.ytimg.com/vi/JgbhJAwYlz8/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Leva', 'https://cdn.dribbble.com/users/1375864/screenshots/13968276/05-logo-mockup.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Repórter Justiça: Quem são as pessoas em situação de rua no país', 'https://i.ytimg.com/vi/9kcceO9J-mI/hqdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Antes que vire lixo', 'https://i.ytimg.com/vi/dFOinVYIzHE/sddefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Moradores de Rua: Encontros, Histórias e Memórias', 'https://i1.sndcdn.com/visuals-000280440782-XIx0hj-t1240x260.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'MORADORES DE RUA: o que podemos fazer por eles?', 'https://www.tvgazeta.com.br/wp-content/uploads/2015/02/ass-cidade-ocupada-web-300x169.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Olho da Rua', 'https://i.ytimg.com/vi/EQxgMvJq6ZU/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Inclusão da população em situação de rua no Cadastro Único', 'http://www.mds.gov.br/webarquivos/sala_de_imprensa/marcas_selos/cadastro-unico/LOGO_CADASTRO_UNICO.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Eu Existo', 'https://i.ytimg.com/vi/dW_SGHrlIjc/mqdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Invisíveis: Moradores de Rua', 'https://www.gesuas.com.br/blog/wp-content/uploads/2018/04/pessoas-em-situacao-de-rua-1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Morar na Rua', 'https://mairalemos.com/wp-content/uploads/2020/10/logo-maira.png');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Das Ruas ao Tribunal', 'https://i.ytimg.com/vi/zJob5VEjqxQ/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Conexão Repórter: Vida e Morte no Concreto de Gelo', 'https://tvsd.com.br/wp-content/uploads/2017/09/conexao-reporter.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aumento da População em Situação de Rua: Tema para o Enem', 'https://i.ytimg.com/vi/HA8OuF06rRY/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Equidade: Campanha Nacional para População em Situação de Rua', 'https://pbs.twimg.com/profile_images/1478451798692306947/6_sTByE-_400x400.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Políticas públicas voltadas para população de rua são debatidas no Cenas do Brasil', 'https://i.ytimg.com/vi/M-yFZdffsus/hqdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Entre Vistas - Padre Júlio Lancellotti', 'https://i.ytimg.com/vi/ZXkH0Zcqb3I/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Documento Verdade: Situação de moradores de rua', 'https://simbacontent.com/wp-content/uploads/2021/07/Documento-Verdade.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Maringá Invisível - População em situação de rua', 'https://www.observatoriodasmetropoles.net.br/wp-content/uploads/2018/09/Pesquisa-Maring%C3%A1-1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'População em situação de rua cresce com a pandemia', 'https://upload.wikimedia.org/wikipedia/pt/1/19/Fala_Brasil.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Provocações 61 com moradores de rua - bloco 01', 'https://portal4.files.wordpress.com/2016/07/cultura-1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'População em situação de rua e o espaço urbano', 'http://tecidades.sites.uff.br/wp-content/uploads/sites/61/2017/03/perfil.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Consultório na Rua - Conhecer para acolher', 'https://www.observatoriodasmetropoles.net.br/wp-content/uploads/2020/04/fiocruz-1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Consultório na Rua', 'https://i1.sndcdn.com/avatars-000490749603-cxr0al-original.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vozes da Rua', 'https://i.ytimg.com/vi/m_cYtuTQVoA/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Andarilhos lutam contra violência para sobreviver nas ruas', 'https://upload.wikimedia.org/wikipedia/pt/1/1e/Logotipo_do_Rep%C3%B3rter_Record_Investiga%C3%A7%C3%A3o.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fala Psi - Populações em Situação de Rua', 'https://i.ytimg.com/vi/7BsZ3pO_WwE/maxresdefault.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pensamento Jurídico - Direitos da população em situação de rua', 'https://www.amb.com.br/wp-content/uploads/2014/12/AMAGISN.png');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);
